In [8]:
import pandas as pd

# Ruta del archivo txt
archivo = 'IPC.txt'
df_ipc = pd.read_csv(archivo, delimiter='\t')

df_ipc.head(5)

     Períodos IPC_1 Petroleo_1 Cobre_6 Desempleo_12   IPC
0  2011-03-01  0,23      89,53    3,50         9,23  0,76
1  2011-04-01  0,76     102,92    3,76         8,84  0,32
2  2011-05-01  0,32     109,96    3,84         9,09  0,40
3  2011-06-01  0,40     101,28    4,15         8,66  0,17
4  2011-07-01  0,17      96,25    4,33         8,51  0,13

In [9]:
import pandas as pd

df_ipc['IPC'] = df_ipc['IPC'].str.replace(',', '.') #Reemplazar comas por puntos y eliminar caracteres no numéricos
df_ipc['Petroleo_1'] = df_ipc['Petroleo_1'].str.replace(',', '.')
df_ipc['Cobre_6'] = df_ipc['Cobre_6'].str.replace(',', '.')
df_ipc['Desempleo_12'] = df_ipc['Desempleo_12'].str.replace(',', '.')

df_ipc['IPC'] = df_ipc['IPC'].str.replace('[^0-9.-]', '') #Eliminar caracteres no numéricos por espacios en blanco
df_ipc['Petroleo_1'] = df_ipc['Petroleo_1'].str.replace('[^0-9.-]', '')
df_ipc['Cobre_6'] = df_ipc['Cobre_6'].str.replace('[^0-9.-]', '')
df_ipc['Desempleo_12'] = df_ipc['Desempleo_12'].str.replace('[^0-9.-]', '')

df_ipc['IPC'] = pd.to_numeric(df_ipc['IPC'], errors='coerce') #Convertir las columnas a tipo numérico
df_ipc['Petroleo_1'] = pd.to_numeric(df_ipc['Petroleo_1'], errors='coerce')
df_ipc['Cobre_6'] = pd.to_numeric(df_ipc['Cobre_6'], errors='coerce')
df_ipc['Desempleo_12'] = pd.to_numeric(df_ipc['Desempleo_12'], errors='coerce')

df_ipc.head(5)

     Períodos IPC_1  Petroleo_1  Cobre_6  Desempleo_12   IPC
0  2011-03-01  0,23       89.53     3.50          9.23  0.76
1  2011-04-01  0,76      102.92     3.76          8.84  0.32
2  2011-05-01  0,32      109.96     3.84          9.09  0.40
3  2011-06-01  0,40      101.28     4.15          8.66  0.17
4  2011-07-01  0,17       96.25     4.33          8.51  0.13

In [10]:
#verificar la calidad de los datos

if df_ipc.isnull().any().any(): #Verificar integridad de los datos
    print("El DataFrame contiene valores faltantes.\n")
missing_values = df_ipc.isnull().sum()
if missing_values.any():
    print(f"{missing_values.sum()} valores faltantes en total.\n")

#verificar valores atípicos en la columna IPC
mean_ipc = df_ipc['IPC'].mean() #Calcular la media y la desviación estándar
std_ipc = df_ipc['IPC'].std()
outliers_ipc = df_ipc.loc[(df_ipc['IPC'] > mean_ipc + 3 * std_ipc) | (df_ipc['IPC'] < mean_ipc - 3 * std_ipc)]
if not outliers_ipc.empty:
    print("El DataFrame contiene valores atípicos en la columna IPC:\n", outliers_ipc, "\n")

#valores negativos en la columna IPC
negativos_ipc = df_ipc.loc[df_ipc['IPC'] < 0]
if not negativos_ipc.empty:
    print("El DataFrame contiene valores negativos en la columna IPC:\n", negativos_ipc, "\n")

#verificar valores atípicos en la columna Petroleo_1
mean_petroleo = df_ipc['Petroleo_1'].mean() #Calcular la media y la desviación estándar
std_petroleo = df_ipc['Petroleo_1'].std()
outliers_petroleo = df_ipc.loc[(df_ipc['Petroleo_1'] > mean_petroleo + 3 * std_petroleo) | (df_ipc['Petroleo_1'] < mean_petroleo - 3 * std_petroleo)]
if not outliers_petroleo.empty:
    print("El DataFrame contiene valores atípicos en la columna Petroleo_1:\n", outliers_petroleo, "\n")


#verificar valores atípicos en la columna Cobre_6
mean_cobre = df_ipc['Cobre_6'].mean() #Calcular la media y la desviación estándar
std_cobre = df_ipc['Cobre_6'].std()
outliers_cobre = df_ipc.loc[(df_ipc['Cobre_6'] > mean_cobre + 3 * std_cobre) | (df_ipc['Cobre_6'] < mean_cobre - 3 * std_cobre)]
if not outliers_cobre.empty:
    print("El DataFrame contiene valores atípicos en la columna Cobre_6:\n", outliers_cobre, "\n")

#verificar valores atípicos en la columna Desempleo_12
mean_desempleo = df_ipc['Desempleo_12'].mean() #Calcular la media y la desviación estándar
std_desempleo = df_ipc['Desempleo_12'].std()
outliers_desempleo = df_ipc.loc[(df_ipc['Desempleo_12'] > mean_desempleo + 3 * std_desempleo) | (df_ipc['Desempleo_12'] < mean_desempleo - 3 * std_desempleo)] # mayor o menor a 3 desviaciones estándar
if not outliers_desempleo.empty:
    print("El DataFrame contiene valores atípicos en la columna Desempleo:\n", outliers_desempleo, "\n")

El DataFrame contiene valores atípicos en la columna IPC:
        Períodos IPC_1  Petroleo_1  Cobre_6  Desempleo_12   IPC
132  2022-03-01  0,29       91.74     4.23         10.35  1.85
141  2022-12-01  0,98       84.78     4.10          7.19  3.28

El DataFrame contiene valores negativos en la columna IPC:
        Períodos  IPC_1  Petroleo_1  Cobre_6  Desempleo_12   IPC
15   2012-06-01   0,03       94.68     3.43          7.21 -0.30
16   2012-07-01  -0,30       82.36     3.65          7.55 -0.01
20   2012-11-01   0,56       89.52     3.59          7.33 -0.45
21   2012-12-01  -0,45       86.68     3.37          6.81 -0.03
25   2013-04-01   0,38       92.91     3.66          6.76 -0.48
26   2013-05-01  -0,48       92.02     3.49          6.94 -0.01
45   2014-12-01   0,02       75.81     3.09          5.78 -0.41
56   2015-11-01   0,41       46.20     2.86          6.21 -0.03
69   2016-12-01   0,05       45.57     2.10          5.87 -0.20
75   2017-06-01   0,13       48.50     2.57          7.02 -0.39
78   2017-09-01   0,20       48.03     2.64          7.03 -0.15
92   2018-11-01   0,37       70.75     3.09          6.70 -0.01
93   2018-12-01  -0,01       56.67     3.15          6.51 -0.10
109  2020-04-01   0,33       29.88     2.60          7.10 -0.04
110  2020-05-01  -0,04       16.52     2.66          7.23 -0.05
111  2020-06-01  -0,05       28.56     2.75          7.25 -0.07
116  2020-11-01   0,69       39.53     2.37          6.96 -0.14

El DataFrame contiene valores atípicos en la columna Desempleo:
        Períodos IPC_1  Petroleo_1  Cobre_6  Desempleo_12   IPC
123  2021-06-01  0,27       65.18     3.52         12.22  0.08
124  2021-07-01  0,08       71.38     3.62         13.09  0.81
125  2021-08-01  0,81       72.46     3.84         12.91  0.36
126  2021-09-01  0,36       67.73     4.08         12.35  1.18